#!/usr/bin/python3

def add_integer(a, b=98):
    """
    Addition function

    Adds two integer, 'x' and 'y' and returns the value of the addition

    Usage:
    >>> add_integer(2, 3)
    5
    >>> add_integer(-5, 10)
    5
    >>> add_integer(hello, 10)
    a must be an integer
    >>> add_integer(34, hello)
    b must be an integer
    """

    if not (isinstance(a, int) or isinstance(a, float)):
        raise TypeError("a must be an integer")
    if not (isinstance(b, int) or isinstance(b, float)):
        raise TypeError("b must be an integer")

    return int(a) + int(b)
